exports.paymentPlans = [
  {
    index: 0,
    planName: "Beacon",
    amount: 20,
    storageInGB: 5,
    dedicatedGateway: 1,
    bandwidthInGB: 10,
    encryptionAccessControl: "mainnet",
    totalNumOfDeduction: 1,
    imageResize: "yes",
    payInCrypto: "yes",
    filecoinDeals: "yes",
  },
  {
    index: 1,
    planName: "Navigator",
    amount: 100,
    storageInGB: 25,
    dedicatedGateway: 1,
    bandwidthInGB: 50,
    encryptionAccessControl: "mainnet",
    totalNumOfDeduction: 1,
    imageResize: "yes",
    payInCrypto: "yes",
    filecoinDeals: "yes",
  },
  {
    index: 2,
    planName: "Harbor",
    amount: 500,
    storageInGB: 150,
    dedicatedGateway: 1,
    bandwidthInGB: 300,
    encryptionAccessControl: "mainnet",
    totalNumOfDeduction: 1,
    imageResize: "yes",
    payInCrypto: "yes",
    filecoinDeals: "yes",
  },
  {
    index: 3,
    planName: "Lite",
    amount: 50,
    storageInGB: 100,
    dedicatedGateway: 1,
    bandwidthInGB: 200,
    encryptionAccessControl: "mainnet",
    totalNumOfDeduction: 1,
    imageResize: "yes",
    payInCrypto: "yes",
    filecoinDeals: "yes",
  },
  {
    index: 4,
    planName: "Premium",
    amount: 100,
    storageInGB: 250,
    dedicatedGateway: 1,
    bandwidthInGB: 500,
    encryptionAccessControl: "mainnet",
    totalNumOfDeduction: 1,
    imageResize: "yes",
    payInCrypto: "yes",
    filecoinDeals: "yes",
  },
];

exports.ipfsPlans = [
  {
    index: 0,
    planName: "Beacon",
    amount: 5,
    storageInGB: 5,
    dedicatedGateway: 1,
    bandwidthInGB: 10,
    encryptionAccessControl: "mainnet",
    totalNumOfDeduction: 1,
    imageResize: "yes",
    payInCrypto: "yes",
    filecoinDeals: "yes",
  },
  {
    index: 1,
    planName: "Navigator",
    amount: 20,
    storageInGB: 25,
    dedicatedGateway: 1,
    bandwidthInGB: 50,
    encryptionAccessControl: "mainnet",
    totalNumOfDeduction: 1,
    imageResize: "yes",
    payInCrypto: "yes",
    filecoinDeals: "yes",
  },
  {
    index: 2,
    planName: "Harbor",
    amount: 50,
    storageInGB: 150,
    dedicatedGateway: 1,
    bandwidthInGB: 300,
    encryptionAccessControl: "mainnet",
    totalNumOfDeduction: 1,
    imageResize: "yes",
    payInCrypto: "yes",
    filecoinDeals: "yes",
  },
];
